Add helm chart for cloudwatch
aws/eks-distro-build-tooling pull request #34
Opened 2020-12-02 17:07 UTC by bnrjee

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2020-12-02 17:51 UTC, abhinavmpandey08 commented on helm-charts/stable/cloudwatch-agent/Chart.yaml
> +version: 0.1.0
Can you set the initial version and app version to 1.0.0 to match our other charts?
https://github.com/aws/eks-distro-build-tooling/blob/main/helm-charts/stable/prow-data-plane/Chart.yaml#L32-L37
https://github.com/aws/eks-distro-build-tooling/blob/main/helm-charts/stable/prow-control-plane/Chart.yaml#L32-L37

2020-12-02 17:51 UTC, abhinavmpandey08 commented on helm-charts/stable/cloudwatch-agent/Chart.yaml
> +appVersion: 1.16.0
Can you set the initial version and app version to 1.0.0 to match our other charts?
https://github.com/aws/eks-distro-build-tooling/blob/main/helm-charts/stable/prow-data-plane/Chart.yaml#L32-L37
https://github.com/aws/eks-distro-build-tooling/blob/main/helm-charts/stable/prow-control-plane/Chart.yaml#L32-L37

2020-12-02 18:03 UTC, abhinavmpandey08 commented
Can you also add the following apache license to all yamls in templates/ and Chart.yaml and values.yaml
https://github.com/aws/eks-distro-build-tooling/blob/main/helm-charts/stable/prow-control-plane/Chart.yaml#L1-L13

2020-12-02 18:47 UTC, abhinavmpandey08 commented
/lgtm

2020-12-02 18:57 UTC, abhinavmpandey08 commented
/approve

2020-12-09 19:03 UTC, bnrjee commented
/test amazon-eks-pod-identity-webhook-tooling-presubmit

2020-12-15 15:15 UTC, TerryHowe commented
Is this good to go or outdated?

2020-12-23 01:30 UTC, micahhausler requested changes
Thanks for this! one change requested

2021-01-04 17:50 UTC, bnrjee commented
/retest

2021-01-05 17:43 UTC, bnrjee commented
These changes will be tracked with 
https://github.com/aws/eks-distro-build-tooling/pull/82

2021-01-05 17:43 UTC, closed without merging